import Alert from "@mui/material/Alert";

import { t } from "../../nonview/base/I18N";
import TrustedSource from "../../nonview/core/TrustedSource";

export default function TrustedSourceView({ publicKey }) {
  if (!publicKey) {
    return null;
  }
  const trustedSource = TrustedSource.getFromPublicKey(publicKey);

  let severity, message;
  if (trustedSource) {
    severity = "success";
    message = (
      <>
        {t("This token has been generated by a trusted source party:")}
        <strong>{" " + trustedSource.name}</strong>
      </>
    );
  } else {
    severity = "warning";
    message = t("This token has been generated by an untrusted source party.");
  }

  return <Alert severity={severity}>{message}</Alert>;
}
